<?php

namespace Uniteam\PresentationBundle\Repository;

/**
 * DbpediacharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DbpediacharacterRepository extends \Doctrine\ORM\EntityRepository
{
}
