<?php

namespace Uniteam\PresentationBundle\Repository;

/**
 * dbupdatehistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dbupdatehistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
