<?php

namespace Uniteam\PresentationBundle\Repository;

/**
 * DbupdatehistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DbupdatehistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
