<?php

namespace Uniteam\PresentationBundle\Repository;

/**
 * FamouscharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamouscharacterRepository extends \Doctrine\ORM\EntityRepository
{
}
